export default {
  json: [],
  isLoading: null,
  missingLocales: [],
  availableLocales: [],
  currentItem: null,
  createItem: null,
  addItem: null,
  addLocale: null,
  removeItem: null,
  menuIsOpen: false,
  isSummaryOpen: false,
  isExportOpen: false,
  filter: null,
  localeIsDisabled: false,
  emptiesOnly: false,
  search: null,
  stats: {},
  locales: []
}
